In [ ]:
 !pip freeze

In [2]:
import plotly
plotly.__version__

'5.24.1'

# PLOTLY EXPRESS

In [3]:
import plotly.express as px

df = px.data.iris()
df.head(2)

   sepal_length  sepal_width  petal_length  petal_width species  species_id
0           5.1          3.5           1.4          0.2  setosa           1
1           4.9          3.0           1.4          0.2  setosa           1

In [5]:
fig = px.scatter(df,x='sepal_width',y='sepal_length',color='species')

fig.show()

# GRAFICOS CON DATASET PENGUINS

In [6]:
import pandas as pd
import seaborn as sns

penguins_df = sns.load_dataset('penguins')
penguins_df.head(2)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female

In [7]:
fig = px.scatter(penguins_df,
                 x='bill_length_mm',
                 y='bill_depth_mm',
                 color='species',
                 title='Relación entre bill_length y bill_depth')
fig.show()